"""Synthetic public dictionary seed. Short original summaries, not long quotations."""

SEED_SOURCES = [
    {
        "id": "src_gita",
        "tradition": "hindu",
        "work": "Bhagavad Gita",
        "reference": "selected chapters",
        "translation": "public-domain edition",
        "license": "public-domain",
        "text": "The Gita discusses duty, action, and release from the binding results of action.",
        "topic_tags": ["dharma", "karma", "moksha"],
    },
    {
        "id": "src_dhammapada",
        "tradition": "buddhist",
        "work": "Dhammapada",
        "reference": "selected verses",
        "translation": "public-domain edition",
        "license": "public-domain",
        "text": "The Dhammapada teaches that intention shapes experience and that craving feeds suffering.",
        "topic_tags": ["karma", "suffering", "nirvana"],
    },
    {
        "id": "src_kjv",
        "tradition": "christian",
        "work": "Bible (KJV)",
        "reference": "selected passages",
        "translation": "KJV",
        "license": "public-domain",
        "text": "The KJV speaks of grace, faith, compassion, and salvation as gifts and practices in Christian life.",
        "topic_tags": ["grace", "faith", "salvation"],
    },
]

def _term(term_id, name, definition, hindu, buddhist, christian, parallel, difference):
    return {
        "id": term_id,
        "term": name,
        "short_definition": definition,
        "tradition_tags": ["hindu", "buddhist", "christian"],
        "hindu_context": hindu,
        "buddhist_context": buddhist,
        "christian_bridge": christian,
        "parallel_text": parallel,
        "difference_text": difference,
        "source_ids": ["src_gita", "src_dhammapada", "src_kjv"],
    }


SEED_TERMS = [
    _term(
        "term_karma",
        "karma",
        "Action and its consequences, understood differently in each tradition.",
        "In Hindu teaching, karma is action and the moral residue that shapes future experience. It is not a simple punishment score.",
        "In Buddhist teaching, karma is intentional action. Intention, more than the outward deed alone, carries consequence.",
        "Christians may recognize a concern for moral consequence, but they do not treat karma as the means of salvation. Forgiveness and grace are a different claim.",
        "Both traditions treat action as morally weighted. That resemblance is an analogy, not one shared doctrine.",
        "Hindu karma includes the residue of action. Buddhist karma centers on intention. Neither account is Christian salvation.",
    ),
    _term(
        "term_dharma",
        "dharma",
        "Duty, teaching, or the way things ought to be held, depending on the tradition.",
        "Hindu dharma includes duty shaped by role, stage of life, and what sustains order.",
        "Buddhist dharma is the teaching of the Buddha and the way that teaching is practiced.",
        "A Christian comparison is moral duty under God, not an identical concept. The obligations are framed by covenant and love of neighbor.",
        "Each tradition uses dharma for something that ought to be held or practiced. The overlap is only that broad.",
        "Hindu dharma is duty in an ordered life. Buddhist dharma is the Buddha's teaching. Those are not the same obligation.",
    ),
    _term(
        "term_moksha",
        "moksha",
        "Hindu term for release from the cycle of rebirth.",
        "Moksha is liberation from samsara, described differently across Hindu schools.",
        "Buddhists more often speak of nirvana than moksha. The aims are related in conversation and not the same doctrine.",
        "Christian hope is resurrection and life with God, not release from a rebirth cycle. Do not treat the words as equivalents.",
        "Moksha and nirvana are sometimes set side by side because both speak of release. That is a conversation analogy, not identity.",
        "Moksha is a Hindu term for liberation from rebirth. Buddhist teaching more often says nirvana, and the doctrines are not the same.",
    ),
    _term(
        "term_nirvana",
        "nirvana",
        "Buddhist term for the cessation of craving and the peace that follows.",
        "Hindu texts may speak of liberation in other words, such as moksha. Nirvana is not the standard Hindu term.",
        "Nirvana is the blowing out of the fires of greed, hatred, and delusion. It is not a place one travels to.",
        "Christians should not rename heaven as nirvana. The Buddhist claim and the Christian hope answer different questions.",
        "People compare nirvana with other words for liberation. The comparison only marks a shared interest in freedom from what binds.",
        "Nirvana is the cessation of craving in Buddhist teaching. It is not moksha, and it is not the Christian heaven.",
    ),
    _term(
        "term_grace",
        "grace",
        "In Christian teaching, God's unearned favor. Other traditions do not use the word the same way.",
        "Hindu devotion includes divine help, but that help is not the Christian doctrine of grace.",
        "Buddhist practice emphasizes intention, ethics, and insight more than unearned divine favor.",
        "Grace in the New Testament is favor given, not earned. It is a specifically Christian claim about God and Christ.",
        "Other traditions speak of divine help or of a path that supports the practitioner. That is not the same as grace.",
        "Hindu devotion and Buddhist practice do not teach unearned favor from the God of the New Testament.",
    ),
    _term(
        "term_faith",
        "faith",
        "Trust or conviction. The object of that trust differs by tradition.",
        "Hindu faith often means trust in a deity, guru, or path, alongside knowledge and practice.",
        "Buddhist confidence (saddha) supports practice. It is not belief that replaces insight.",
        "Christian faith is trust in God revealed in Christ. It is not a generic word for any strong belief.",
        "Each tradition asks for trust that leads into a way of life. The word faith does not name the same object of trust.",
        "Hindu trust may rest on a deity or guru. Buddhist confidence supports practice and insight. Christian faith trusts Christ.",
    ),
    _term(
        "term_meditation",
        "meditation",
        "Trained attention. The goal of the practice is not the same in each tradition.",
        "Hindu meditation includes disciplines aimed at steadiness, devotion, or knowledge of the self.",
        "Buddhist meditation trains attention and insight into impermanence, suffering, and non-self.",
        "Christian prayer and contemplation address God. Silence can be shared as a practice without claiming the same goal.",
        "Stillness and trained attention appear in all three. Sharing the practice does not mean sharing the goal.",
        "Hindu meditation may seek the self or a deity. Buddhist meditation seeks insight into suffering and non-self. Christian prayer addresses God.",
    ),
    _term(
        "term_suffering",
        "suffering",
        "Pain and dissatisfaction, explained with different causes and hopes.",
        "Hindu accounts often tie suffering to karma, ignorance, and the cycle of rebirth.",
        "Buddhism names suffering (dukkha) as a basic feature of unawakened life, fed by craving.",
        "Christians locate suffering in a broken world and look to God's presence and final restoration, not only to technique.",
        "All three traditions take pain seriously and refuse to treat it as meaningless. That is the parallel.",
        "Hindu and Buddhist accounts tie suffering to karma, ignorance, or craving. The Christian account is a broken world and God's restoration.",
    ),
    _term(
        "term_compassion",
        "compassion",
        "A moral response to another's pain, praised across these traditions.",
        "Hindu ethics include daya, tender regard for living beings, alongside duty.",
        "Buddhist compassion (karuna) is a central virtue, paired with wisdom rather than sentiment alone.",
        "Christian compassion follows the command to love the neighbor and the example of Jesus. The moral overlap is real; the theology is not identical.",
        "Regard for another's pain is praised in Hindu daya, Buddhist karuna, and Christian love of neighbor. The moral overlap is real.",
        "The virtues are not the same doctrine. Buddhist compassion is paired with insight into non-self. Christian compassion follows Jesus.",
    ),
    _term(
        "term_salvation",
        "salvation",
        "A Christian word for being rescued and reconciled to God.",
        "Hindu liberation is usually moksha, not salvation in the Christian sense.",
        "Buddhist freedom is described as nirvana or awakening, not rescue by grace.",
        "Salvation in Christian teaching is God's rescue through Christ. Using the word for every tradition blurs that claim.",
        "People reach for one word when they hear moksha, nirvana, and salvation. The parallel is only the human hope of being freed.",
        "Hindu liberation and Buddhist awakening are not rescue by grace. Calling all three salvation forces a false equivalence.",
    ),
]
